### PR TITLE
Added more attributes to the xss whitelist

### PR DESCRIPTION
**Pull request by RagingLink**
Added `style`, `title` and `data-tooltip` to the whitelisted attributes for the output page. I went through the attribute list to see if there are perhaps more attributes blarg could support, but I didn't really find anything 'worth' adding.

**Added:**
- `style`, `title` and `data-tooltip` to the global attribute whitelist.

Stems from a feature request in `#bb-support`:
image

### CODE REVIEW

**Comment by HunteRoi** [comment]
Watch out with `data-` attributes, they could be used by javascript libraries and could lead to flaws in the security of the bot.

**Comment by RagingLink** [comment]
> Watch out with `data-` attributes, they could be used by javascript libraries and could lead to flaws in the security of the bot.

Can't quite say I understand where you're coming from tbh.

~~I was typing out some examples to explain my view, but I honestly cannot see how it'd impact the security server-side~~

**Review by danny-may — APPROVED** [review]

**Review by HunteRoi — APPROVED** [review]
My previous comment was just a warning. Not all `data-` attribute should be whitelisted.

But this list is fine! Thank you :smile:

**Comment by RagingLink** [comment]
> 
> 
> My previous comment was just a warning. Not all `data-` attribute should be whitelisted.
> 
> But this list is fine! Thank you 😄

Ah yeah that's understandable o/ Your previous comment confused me a bit as `data-tooltip` shouldn't be an issue

**Pull request merged**
