### PR TITLE
Update package versions

### PR DESCRIPTION
**Pull request by danny-may**

### CODE REVIEW

**Comment by danny-may** [comment]
Seems typescript 4.8.4 isnt supported by yarn berry yet, waiting until their fix is deployed before this PR can go through
https://github.com/yarnpkg/berry/issues/4915

**Comment by HunteRoi** [comment]
I saw you updated mocha to 10.0.0. Isn't there breaking changes ? I don't see any update in test files... 🤔

**Comment by danny-may** [comment]
Mocha was updated in the last dependency update I did, this is just the update to the typings

**Comment by HunteRoi** [comment]
@danny-may What about the builds failing?

**Review by HunteRoi — APPROVED** [review]

**Comment by danny-may** [comment]
Thats due to the yarn issue. Basically because dependencies are zipped files in `.yarn/cache` rather than normal folders in `node_modules`, yarn needs to inject in the logic to typescript to enable module lookups. 
Without the fix from yarn, typescript cannot find any of the projects dependencies and so fails to build

**Pull request merged**
